name: theraconnect
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0  # Use the latest version
  firebase_auth: ^5.8.0  # Use a compatible version
  cloud_firestore: ^5.9.0  # Use a compatible version
  firebase_storage: ^11.4.0  # Use the latest version
  livekit_client: ^2.2.6  # Use the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
