name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this if you are using a different branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your preferred Node.js version

      - name: Install dependencies
        run: npm install  # Use 'yarn install' if you are using Yarn

      - name: Build the app
        run: npm run build  # Use 'yarn build' if you are using Yarn

      - name: Deploy to Netlify
        uses: netlify/actions/setup-netlify@v1
        with:
          publish-dir: ./build  # Ensure this path matches your build output directory
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
